/** Supplied Speedex Design copy. Prices are supplied placeholders pending owner confirmation. */
export const digitalServices = [
  ['Social Media Management', 'Content planning, posting, community management and growth on Instagram, Facebook, LinkedIn, TikTok and X.', 'إدارة وسائل التواصل الاجتماعي', 'تخطيط المحتوى ونشره وإدارة المجتمع وتنمية الحضور على إنستغرام وفيسبوك ولينكدإن وتيك توك وإكس.'],
  ['Content & Creative Design', 'Posts, reels, carousels, banners, brochures and branded templates designed to stop the scroll.', 'المحتوى والتصميم الإبداعي', 'منشورات ومقاطع قصيرة وتصاميم وبروشورات وقوالب تعكس هوية علامتك التجارية.'],
  ['Paid Advertising (Meta, Google, LinkedIn, TikTok)', 'Targeted ad campaigns built to bring enquiries, calls and sales, with budgets optimised weekly.', 'الإعلانات المدفوعة', 'حملات إعلانية موجهة لتحقيق الاستفسارات والمكالمات والمبيعات مع تحسين الميزانية أسبوعياً.'],
  ['Search Engine Optimization (SEO)', 'Rank higher on Google for the services your customers search for, in English and Arabic.', 'تحسين محركات البحث', 'تحسين ظهور خدماتك على جوجل باللغة الإنجليزية والعربية.'],
  ['Google Business Profile & Local SEO', 'Get found on Google Maps and "near me" searches, with reviews and listing management.', 'ملف النشاط التجاري والبحث المحلي', 'عزّز ظهورك على خرائط جوجل ونتائج البحث المحلي مع إدارة التقييمات والملف التجاري.'],
  ['Website Design & Development', 'Fast, modern, mobile-friendly websites and landing pages built to convert visitors into leads.', 'تصميم وتطوير المواقع', 'مواقع وصفحات هبوط سريعة وعصرية ومتوافقة مع الهاتف لتحويل الزوار إلى عملاء محتملين.'],
  ['Corporate Lead Generation', 'B2B outreach, LinkedIn campaigns and email marketing to bring qualified corporate clients to your sales team.', 'استقطاب عملاء الشركات', 'حملات لينكدإن والتواصل المباشر والتسويق بالبريد لجذب عملاء شركات مؤهلين.'],
  ['Video & Reel Production', 'Short-form promotional videos, product showcases and company profile videos.', 'إنتاج الفيديو والمقاطع القصيرة', 'مقاطع ترويجية قصيرة وعروض للمنتجات وفيديوهات تعريفية بالشركة.'],
  ['Branding & Brand Identity', 'Logo, brand guidelines, company profile and portfolio design that make your business look credible.', 'العلامة والهوية التجارية', 'تصميم الشعار ودليل الهوية والملف التعريفي ومعرض الأعمال لبناء حضور موثوق.'],
  ['Email & WhatsApp Marketing', 'Campaigns and automated follow-ups that keep customers coming back.', 'التسويق بالبريد وواتساب', 'حملات ومتابعات آلية للحفاظ على تواصل العملاء مع علامتك.'],
  ['Analytics & Reporting', 'Clear monthly dashboards showing reach, leads, cost per lead and what to improve next.', 'التحليلات والتقارير', 'تقارير شهرية واضحة عن الوصول والعملاء المحتملين وتكلفة الحصول عليهم وفرص التحسين.'],
  ['Online Reputation Management', 'Review collection, response handling and reputation monitoring.', 'إدارة السمعة الإلكترونية', 'جمع التقييمات والرد عليها ومراقبة السمعة الرقمية.'],
] as const;
export const digitalSteps = [
  ['Discover', 'We learn your business, customers, competitors and goals.', 'الاستكشاف', 'نتعرف إلى نشاطك وعملائك ومنافسيك وأهدافك.'],
  ['Strategy', 'We build a clear plan covering channels, content, budget and targets.', 'الاستراتيجية', 'نضع خطة واضحة للقنوات والمحتوى والميزانية والأهداف.'],
  ['Create', 'Our team designs and produces your content, ads and assets.', 'الإبداع', 'يصمم فريقنا المحتوى والإعلانات والمواد اللازمة.'],
  ['Launch', 'Campaigns go live after your approval.', 'الإطلاق', 'تبدأ الحملات بعد موافقتك.'],
  ['Optimise', 'We track performance weekly and adjust to improve results.', 'التحسين', 'نتابع الأداء أسبوعياً ونجري التعديلات لتحسين النتائج.'],
  ['Report', 'You receive a clear monthly report and a call to review progress.', 'التقرير', 'تتلقى تقريراً شهرياً واضحاً ومكالمة لمراجعة التقدم.'],
] as const;
export const digitalPackages = [
  {name:'Starter', ar:'الانطلاقة', price:'2,500', audience:'Best for small businesses starting their online presence', audienceAr:'للشركات الصغيرة التي تبدأ حضورها الرقمي', features:['2 social media platforms','12 designed posts per month','2 reels per month','Content calendar and caption writing','Basic hashtag and audience setup','Google Business Profile setup and updates','Monthly performance report','WhatsApp support'], featuresAr:['منصتان للتواصل الاجتماعي','12 منشوراً مصمماً شهرياً','مقطعان قصيران شهرياً','تقويم محتوى وكتابة النصوص','إعداد الوسوم والجمهور الأساسي','إعداد وتحديث ملف النشاط التجاري على جوجل','تقرير أداء شهري','دعم عبر واتساب']},
  {name:'Growth', ar:'النمو', price:'5,500', audience:'Best for businesses ready to generate consistent leads', audienceAr:'للشركات المستعدة لاستقطاب العملاء باستمرار', features:['3 social media platforms','20 designed posts per month','4 reels per month','Paid ad management on Meta and Google (1 campaign set)','Lead generation campaign setup and tracking','Basic SEO and Google Business Profile optimisation','Community management (comments and messages)','Monthly performance report with strategy call','Priority WhatsApp support'], featuresAr:['3 منصات للتواصل الاجتماعي','20 منشوراً مصمماً شهرياً','4 مقاطع قصيرة شهرياً','إدارة إعلانات ميتا وجوجل (مجموعة حملات واحدة)','إعداد حملات جذب العملاء وتتبعها','تحسين أساسي للبحث وملف النشاط التجاري','إدارة التعليقات والرسائل','تقرير شهري ومكالمة استراتيجية','دعم واتساب بأولوية']},
  {name:'Premium', ar:'المتميزة', price:'9,500', audience:'Best for companies that want a complete digital marketing department', audienceAr:'للشركات التي تحتاج إلى فريق تسويق رقمي متكامل', features:['4+ social media platforms, including LinkedIn','30 designed posts and 8 reels per month','Paid ads on Meta, Google, LinkedIn and TikTok','Corporate lead generation (LinkedIn and email outreach)','Full SEO program (English and Arabic)','Landing page design and conversion tracking','Monthly video shoot or production day','Email and WhatsApp marketing campaigns','Online reputation management','Dedicated account manager','Bi-weekly reporting and strategy calls'], featuresAr:['أكثر من 4 منصات بما فيها لينكدإن','30 منشوراً و8 مقاطع قصيرة شهرياً','إعلانات ميتا وجوجل ولينكدإن وتيك توك','استقطاب عملاء الشركات عبر لينكدإن والبريد','برنامج شامل لتحسين البحث بالعربية والإنجليزية','صفحة هبوط وتتبع التحويلات','يوم تصوير أو إنتاج فيديو شهرياً','حملات البريد وواتساب','إدارة السمعة الإلكترونية','مدير حساب مخصص','تقارير ومكالمات استراتيجية كل أسبوعين']},
] as const;
export const digitalAddons = [
  ['Business website (up to 5 pages)','4,500','موقع أعمال (حتى 5 صفحات)'],['Landing page','1,500','صفحة هبوط'],['Logo and brand identity','1,800','الشعار والهوية التجارية'],['Company profile / portfolio design','2,500','الملف التعريفي / معرض الأعمال'],['Promotional video (30–60 sec)','1,500','فيديو ترويجي (30–60 ثانية)'],['Social media account setup and branding','800','إعداد حسابات التواصل وهويتها'],['SEO audit report','1,200','تقرير تدقيق تحسين البحث'],
] as const;
export const digitalReasons = [
  ['Backed by an established group','Part of Excellent Group of Companies, a trusted UAE business.','بدعم مجموعة راسخة','جزء من مجموعة إكسلنت للشركات، اسم موثوق في الإمارات.'],['Real industry experience','We market automotive, transport, contracting, facilities and trading businesses every day.','خبرة واقعية في القطاعات','نسوّق يومياً لشركات السيارات والنقل والمقاولات والمرافق والتجارة.'],['Design and signage expertise','Our link with Speedex Signages means your online and physical branding match perfectly.','خبرة في التصميم واللافتات','ارتباطنا بسبيدكس ساينجز يوحّد هويتك الرقمية والواقعية.'],['Clear, honest reporting','You always know what was done and what it achieved.','تقارير واضحة وصادقة','تعرف دائماً ما أنجزناه وما حققته الحملات.'],['Bilingual content','English and Arabic campaigns for the UAE market.','محتوى بلغتين','حملات بالعربية والإنجليزية للسوق الإماراتي.'],['Fast response','Direct WhatsApp access to your team.','استجابة سريعة','تواصل مباشر مع فريقك عبر واتساب.'],['No long lock-in','Flexible monthly plans.','دون التزام طويل','باقات شهرية مرنة.'],['Results focused','We measure leads and enquiries, not just likes.','التركيز على النتائج','نقيس العملاء المحتملين والاستفسارات لا الإعجابات فقط.'],
] as const;
export const digitalIndustries = [
  ['Automotive & Workshops','السيارات والورش'],['Car Rental','تأجير السيارات'],['Transport & Logistics','النقل والخدمات اللوجستية'],['Facilities Management','إدارة المرافق'],['Construction & Contracting','البناء والمقاولات'],['General Trading','التجارة العامة'],['Signage & Printing','اللافتات والطباعة'],['Real Estate','العقارات'],['Retail','التجزئة'],['Healthcare','الرعاية الصحية'],['Hospitality','الضيافة'],['Corporate & B2B','الشركات والتعامل بين الشركات'],
] as const;
export const digitalFaq = [
  ['Do package prices include ad spend?','No. Ad budgets are paid directly to Meta, Google, LinkedIn or TikTok. Our fee covers strategy, creative, setup, management and reporting. We will recommend a suitable budget for your goals.','هل تشمل الأسعار الإنفاق الإعلاني؟','لا. تُدفع ميزانيات الإعلانات مباشرة للمنصات. تشمل رسومنا الاستراتيجية والتصميم والإعداد والإدارة والتقارير، ونوصي بميزانية تناسب أهدافك.'],
  ['Is there a minimum contract?','We recommend at least 3 months to see meaningful results, but there is no long-term lock-in.','هل توجد مدة تعاقد دنيا؟','ننصح بثلاثة أشهر على الأقل لرؤية نتائج ملموسة، دون التزام طويل الأمد.'],
  ['Can I upgrade or change my package later?','Yes. You can move up or adjust your plan at the start of any month.','هل يمكنني تغيير باقتي لاحقاً؟','نعم، يمكنك ترقية خطتك أو تعديلها في بداية أي شهر.'],
  ['Who owns the content and accounts?','You do. All social accounts, ad accounts, designs and websites remain your property.','لمن تعود ملكية المحتوى والحسابات؟','لك. تبقى حسابات التواصل والإعلانات والتصاميم والمواقع ملكاً لك.'],
  ['How soon will I see results?','Paid ads can bring enquiries within days. Social media and SEO build steadily over 2–4 months.','متى تظهر النتائج؟','قد تجلب الإعلانات المدفوعة استفسارات خلال أيام، بينما ينمو أثر التواصل الاجتماعي والبحث تدريجياً خلال شهرين إلى أربعة أشهر.'],
  ['Do you create content in Arabic?','Yes. We create content in English and Arabic.','هل تنتجون محتوى بالعربية؟','نعم، ننشئ المحتوى بالعربية والإنجليزية.'],
  ['Do you work with businesses outside Abu Dhabi?','Yes. We serve businesses across the UAE.','هل تعملون خارج أبوظبي؟','نعم، نخدم الشركات في جميع أنحاء الإمارات.'],
  ['How do reports work?','You receive a monthly report covering reach, engagement, leads, cost per lead and recommended next steps.','كيف تعمل التقارير؟','تتلقى تقريراً شهرياً عن الوصول والتفاعل والعملاء المحتملين وتكلفتهم والخطوات التالية الموصى بها.'],
  ['Can you handle multiple branches or companies?','Yes. Our Custom Package is designed for groups and multi-brand businesses.','هل تخدمون شركات متعددة الفروع؟','نعم، صُممت الباقة المخصصة للمجموعات والشركات متعددة العلامات.'],
] as const;
